config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do

    resources :labels

  end


end

app/models/spree/label.rb
class Spree::Label < Spree::Base

  has_and_belongs_to_many :variants, class_name: 'Spree::Variant'

  validates_presence_of :name, :color
  validates_uniqueness_of :name

end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do

  has_and_belongs_to_many :labels, class_name: 'Spree::Label'

end

app/controllers/spree/admin/labels_controller.rb
module Spree
  module Admin
    class LabelsController < ResourceController
      def index
        session[:return_to] = request.url
        respond_with @collection
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        @collection = super
        # @search needs to be defined as this is passed to search_form_for
        Ransack.options[:ignore_unknown_conditions] = false
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
            page(params[:page]).
            per(params[:per_page] || Spree::Config[:admin_products_per_page])
        @collection
      end
    end
  end
end

app/helpers/spree/admin/base_helper_decorator.rb
module Spree
  module Admin
    BaseHelper.class_eval do

      def render_label_color color
        content_tag :div, {class: 'variant-label', style: "background-color: #{color};" } do
          ''
        end
      end
    end
  end
end

app/views/spree/admin/labels/_form.html.erb
<div class="row" data-hook="new_label_attrs">
  <div class="col-md-6">
    <%= f.field_container :name, :class => ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, class: 'form-control title' %>
      <% f.error_message_on :name %>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= f.field_container :color, :class => ['form-group'] do %>
      <%= f.label :color, Spree.t(:color) %>
      <div class="row">
        <div class="col-md-3">
          <input type="text" id="colorpicker" class="form-control" />
        </div>
        <div class="col-md-9">
          <%= f.text_field :color, class: 'form-control color-text' %>
        </div>
      </div>
      <%= f.error_message_on :color %>
    <% end %>
  </div>
</div>
<script type="text/javascript">
  new window.LabelController('<%= @label.color %>');
</script>

app/views/spree/admin/labels/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:labels), admin_labels_path %> /
  <%= @label.name %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_label), new_object_url, {class: 'btn-success', icon: 'add', id: 'admin_new_label'} %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: {target: @label } %>

<%= form_for [:admin, @label], method: :put do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: {f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/labels/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Label) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to Spree.t(:new_label), new_object_url, {class: 'btn-success', icon: 'add', id: 'admin_new_label'} %>
<% end %>

<% content_for :table_filter do %>
  <div class="" data-hook="admin_labels_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="row" data-hook="admin_labels_index_search">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, size: 15, class: 'form-control js-quick-search-target' %>
          </div>
        </div>
      </div>
      <div class="form-actions" data-hook="admin_labels_index_search_buttons">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>


<%= render partial: 'spree/admin/shared/index_table_options', locals: {collection: @collection} %>

<% if @collection.any? %>
  <table class="table" id="listing_labels">
    <thead>
    <tr data-hook="admin_labels_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:color) %></th>
      <th data-hook="admin_labels_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @collection.each do |label| %>
      <tr data-hook="admin_labels_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= label.name %></td>
        <td>
          <%= render_label_color label.color %>
          <%= label.color %>
        </td>
        <td class="actions actions-2 text-right" data-hook="admin_labels_index_row_actions">
          <%= link_to_edit label, no_text: true, class: 'edit' if can? :edit, Spree::Label %>
          <%= link_to_delete label, no_text: true if can? :destroy, Spree::Label %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Label)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: {collection: @collection} %>

app/views/spree/admin/labels/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: {target: @label} %>

<% content_for :page_title do %>
  <%= Spree.t(:new_label) %>
<% end %>

<%= form_for [:admin, @label] do  |f| %>
  <fieldset data-hook="new_label">

    <%= render partial: 'form', locals: {f: f} %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>